version: "3.8"

services:
  app:
    image: openjdk:17-jdk-alpine # Imagem do Java 17
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/db_motorvalidacao
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
    volumes:
      - ./target:/app # Monta o diretório target do Maven/Gradle no container
    working_dir: /app
    command: java -jar nome-do-seu-jar.jar # Substitua pelo nome do seu arquivo JAR

  db:
    image: postgres:14
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: db_motorvalidacao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: